project02/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('wheelShop.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

wheelShop/urls.py
from django.urls import path,include
from . import views

app_name='wheelShop'

urlpatterns=[

    path('',views.MainView.as_view(),name='main'),
    path('parts/',views.parts,name='partsy'),
    path('about/',views.AboutView.as_view(),name='abouty'),
    path('', include('social_django.urls', namespace='social')),
    path('https://mateusz97i1wheelsshop.vercel.app/',views.logout,name='logout'),
    path('profile/',views.profile,name='profile'),
    path('shopping-basket/',views.shoppingBasket,name='shoppingBasket'),
    path('add-to-cart/<int:wheel_id>/', views.add_to_cart, name='add_to_cart'),
    path('remove_from_cart/<int:wheel_id>/',views.remove_from_cart,name='remove_from_cart'),
    path('payment_successful/',views.payment_successful,name='payment_successful'),
    path('payment_cancelled/',views.payment_cancelled,name='payment_cancelled'),
    path('checkout/',views.checkout,name='checkout'),
    path('searched/',views.searched,name='searched'),

    
]


wheelShop/models.py
from django.db import models
from django.core.validators import MaxValueValidator


# Create your models here.

class WheelsModel(models.Model):
    name=models.CharField(max_length=50)
    size=models.IntegerField(validators=[MaxValueValidator(22)])
    price=models.IntegerField()
    leftOnStock=models.IntegerField()
    image=models.CharField(max_length=300)

    def __str__(self):
        return self.name
    

wheelShop/views.py
from django.shortcuts import render, redirect 
from django.views.generic import TemplateView,ListView,View
import datetime
from django import template
from .models import WheelsModel
from django.http import HttpResponseRedirect
from django.contrib.auth import logout as django_logout
from authlib.integrations.django_client import OAuth

from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required
import json
from django.conf import settings
import stripe
from django.urls import reverse, reverse_lazy
import os
from decouple import config
register = template.Library()




# Create your views here.
#Main site page, additionally show clock at the right top corner
class MainView(TemplateView):
    template_name='mainHero.html'

    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['current_time'] = self.clock()
        return context
    
    @staticmethod
    def clock():
            
        return datetime.datetime.now()
    
def searched(request):

    if request.method == 'GET' and 'searchMain' in request.GET and request.GET['searchMain']:
        parts = request.GET['searchMain']
        wheelSearch = WheelsModel.objects.filter(name__icontains=parts)
        return render(request, "searched.html", {'parts': wheelSearch})
    else:
       
        return render(request, "searched.html")

    
   
#Displays all wheels from database
def parts(request):


    wheels = WheelsModel.objects.all()
    context = {'wheels': wheels}
    return render(request, 'parts.html', context)


class AboutView(TemplateView):
    template_name='about.html'

#logout
# https://{domain}/v2/logout?client_id={client_id}&returnTo={return_to}

#Logging Out function from Auth0
def logout(request):
    django_logout(request)

    domain=config('APP_DOMAIN')
    client_id=config('APP_CLIENT_ID')
    return_to='http://localhost:8000/'

    return HttpResponseRedirect(f"https://{domain}/v2/logout?client_id={client_id}&returnTo={return_to}")
    

#user profile Auth0
def profile(request):
    user=request.user

    auth0_user=user.social_auth.get(provider='auth0')

    user_data={
        'user_id':auth0_user.uid,
        'name': auth0_user.extra_data.get(''),
    }

    context={
        'user_data':json.dumps(user_data,indent=4),
        'auth0_user':auth0_user
    }

    return render(request,'profile.html',context)

#basket, What we already have bought
def shoppingBasket(request):


    cart = request.session.get('cart', {})
    wheel_items = []
    total = 0
    # Adds a clear button, if is clicked then the session request, cart/basket will be cleared
    if request.POST:
        request.session['cart'] = {}
        return redirect('wheelShop:shoppingBasket')

    #Adding info to the request session liblary
    for wheel_id, quantity in cart.items():
        wheel = WheelsModel.objects.get(id=wheel_id)
        wheel_items.append({
            'id': wheel_id,
            'name': wheel.name,
            'image': wheel.image,
            'price': wheel.price,
            'quantity': quantity
        })
        #Counting total cost of the cart
        total += wheel.price * quantity

    context = {
        'wheel_items': wheel_items,
        'total': total
    }

    return render(request, 'shoppigBasket.html', context)
    
#add to cart function, saves in our sesion informations
#about bought items
def add_to_cart(request, wheel_id):

    wheel = WheelsModel.objects.get(id=wheel_id) #Takes id of the wheel from WHeelsSHop database

    amount=int(request.POST.get('amount',1)) # Read selected amount or take 1 as the default value

    cart = request.session.get('cart', {}) #creates the cart in browser session

#gets stock amout and checks if we are able to sell choosen amout
    if wheel.leftOnStock < amount:
        amount=wheel.leftOnStock
        cart[wheel_id] = cart.get(wheel_id, 0) + amount
        request.session['cart'] = cart

    else:
        cart[wheel_id] = cart.get(wheel_id, 0) + amount
        request.session['cart'] = cart

    return redirect('wheelShop:shoppingBasket')


def remove_from_cart(request,wheel_id):

    if request.method == 'POST':
        wheel_id = request.POST.get('wheel_id')
        cart = request.session.get('cart', {})
        
        if wheel_id in cart:
            del cart[wheel_id]
            request.session['cart'] = cart

    return redirect('wheelShop:shoppingBasket')


def payment_successful(request):
    return render(request,'success.html')


def payment_cancelled(request):
    return render(request,'cancel.html')


#Takes stripe secret key from setting.py
stripe.api_key=config('STRIPE_SECRET_KEY')

# @login_required
def checkout(request):

    #Gets The total price of the order
    cart = request.session.get('cart', {})
    total = 0

    #loop that counts items and returns total price of our basket/cart
    for wheel_id, quantity in cart.items():
        wheel = WheelsModel.objects.get(id=wheel_id)
        # New function removes bought items(reduces quantity) from the db
        wheel.leftOnStock-=quantity
        wheel.save() 
        total += wheel.price * quantity
        


    #Creating checkout session
    checkout_session = stripe.checkout.Session.create(

        line_items=[
            {
                # Provide the exact Price ID (for example, pr_1234) of the product you want to sell
                'price_data':{
                    'unit_amount':total*100, # Multiplayed 100times because the price is in cents
                    'currency':'pln',
                    'product_data': {
                                    'name': 'Wheels',
                                    },
                }, 
                'quantity': 1,
            },
        ],
        
        mode='payment', #sub mode also u can change it to payment if u already have set it up for that purpose
        success_url=request.build_absolute_uri(reverse('wheelShop:payment_successful')),
        cancel_url=request.build_absolute_uri(reverse('wheelShop:payment_cancelled')),
    )
    #redirects to the stripe payment site
    return redirect(checkout_session.url, code=303)

wheelShop/templates/about.html
{% extends 'mainHero.html'%}
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>About</title>
</head>
<body >
    {% block mainWheelSite %}
    <link rel="stylesheet" href="{% static 'about.css' %}">
    <h1><em>About us</em> </h1>
    <hr>
    <div class="aboutDescriptiono"> 
        <p>WheelsShop is a company based in Poland that specializes in the production and installation of wheels.</p>
        <p>With years of experience in the industry, we are committed to providing high-quality wheels that meet the needs of our customers.</p>
        <p>Our range of products includes alloy wheels, steel wheels, and custom-made wheels that can be tailored to your specific requirements.</p>
        <p>In addition to our production services, we also offer wheel installation, balancing, and alignment services to ensure that your wheels perform at their best.</p>
        <p>At WheelsShop, we believe in providing exceptional customer service and building lasting relationships with our clients. We are dedicated to ensuring your complete satisfaction with our products and services.</p>
        <p>Contact us today to learn more about how we can help you with your wheel needs!</p>
    </div>
    {% endblock %}
</body>

</html>

wheelShop/templates/cancel.html
{% extends 'mainHero.html' %}
{% load static %}

<!DOCTYPE html>
<html>
<head>
  <title>Checkout canceled</title>
</head>
<body>
    
    {% block mainWheelSite %}
          <section style="font-weight: bold; text-align: center; height: 70vh;" >
    <p>Forgot to add something to your cart? Shop around then come back to pay!</p>
  </section>
    {% endblock mainWheelSite %}
        

</body>
</html>

wheelShop/templates/checkout.html
<!DOCTYPE html>
<html>
  <head>
    <title>Buy cool new product</title>
    <link rel="stylesheet" href="style.css">
    <script src="https://js.stripe.com/v3/"></script>
  </head>
  <body>
    <section>
      <div class="product">
        <img src="https://i.imgur.com/EHyR2nP.png" alt="The cover of Stubborn Attachments" />
        <div class="description">
          <h3>Stubborn Attachments</h3>
          <h5>$20.00</h5>
        </div>
      </div>
      <form action="{% url 'wheelShop:checkout'%}" method="POST">
        {% csrf_token %}
        <button type="submit" id="checkout-button">Checkout</button>
      </form>
    </section>
  </body>
</html>

wheelShop/templates/mainHero.html
{% load static %}
<html lang="en">
<head>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat&family=Roboto:wght@300&display=swap" rel="stylesheet">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'main.css' %}">
    <title>WheelShop</title>
</head>
<body>
    
    <section class="searchBar">
        
        <form class="form1" method="get" action="{% url 'wheelShop:searched' %}">
            {% csrf_token %}
            <div id="closeBtn"></div>

            <div class="box0">
                <input placeholder="..." class="input1" type="text" name="searchMain" id="">
                <button type="submit">SEARCH</button>
                
            </div>
            <H4>EXPLORE</H4> 
            <ul>
                <li>WHEELS</li>
                <li>FRONT BUMPERS</li>
                <li>REAR BUMPERS</li>
                <li>ACCESORIES</li>
            </ul>
            
        </form>

    </section>



    <header>
        <div class="box1">WHEELS  ALLOVER  THE  WORLD</div>
        <div class="box2"><a href="{% url 'wheelShop:partsy' %}">EXPLORE OUR NEW COLLECTION</a> </div>
        <div class="box3">POLAND  {{ current_time }}</div>
    </header>
    
    <section class="sectionHead">
        <div class="box4">
            <div class="logo-image" ></div>
            <a href="{% url 'wheelShop:main' %}" class="logo"></a>
            <a href="{% url 'wheelShop:main'%}" class="home" >HOME</a>
            <a href="{% url 'wheelShop:partsy'%}" class="menuBarParts">PARTS</a>
            <a href="{% url 'wheelShop:abouty'%}" class="menuBarAbout">ABOUT</a>
        </div>
        
        <h1> <a href="{% url 'wheelShop:main'%}">W H E E L S H O P</a> </h1>
        <div class="box5">
            <div class="box6"></div>
            
            
            {% if user.is_authenticated %}
            <a class="box7" href="{% url 'wheelShop:profile'%}"> </a>
            <a class="box9" href="{% url 'wheelShop:shoppingBasket'%}"></a>
            <a class="box8" href="/logout"></a> 
            {% else %}
            <a class="box7" href="/login/auth0"> </a>
            {% endif %}
                
        </div>
        
    </section>

    
    <section class="partsBar">

        <div class="partsBox1">
            <div id="boxid0"></div>
            <div id="boxid1"><a id="boxid1-a" href="{% url 'wheelShop:partsy' %}">WHEELS</a></div>
            <div id="boxid2">
                
                <ul>
                    <li>18"</li>
                    <li>19"</li>
                    <li>20"</li>
                </ul>

            </div>
        </div>

        <div class="partsBox1">
            <div id="boxid0"></div>
            <div id="boxid1"><a id="boxid1-a" href="#">FRONT BUMPERS</a></div>
            <div id="boxid2">
               
                <ul>
                    <li>BBS</li>
                    <li>Akrapovic</li>
                </ul>
                
            </div>
        </div>

        <div class="partsBox1">
            <div id="boxid0"></div>
            <div id="boxid1"><a id="boxid1-a" href="#">REAR BUMPERS</a></div>
            <div id="boxid2">
                
                <ul>
                    <li>BBS</li>
                    <li>Akrapovic</li>
                </ul>
                
            </div>
        </div>

        <div class="partsBox1">
            <div id="boxid0"></div>
            <div id="boxid1"><a id="boxid1-a" href="#">ACCESORIES</a></div>
            <div id="boxid2">
                
                <ul>
                    <li>Fridge Magnets</li>
                    <li>T-shirts</li>
                </ul>
                
            </div>
        </div>
        
    </section>

    <section class="aboutBar">

        <div class="partsBox1">
            <div id="boxid0"></div>
            <div id="boxid1"><a id="boxid1-a" href="{% url 'wheelShop:abouty'%}">ABOUT</a></div>
            <div id="boxid2">
                
                <ul>
                    <li>Call US</li>
                </ul>

            </div>
        </div>

    </section>

{% block mainWheelSite %}
{% csrf_token %}
    <section class="sectionImg">
        <div class="description1">
            <h2>Summer is coming!</h2>
            <p>Welcome to a new sezon: our summer collection features
            are ready to explore.</p>
            <a href="{% url 'wheelShop:partsy'%}">EXPLORE NEW SUMMER COLLECTION</a>           
        </div>
    </section>

    <hr>
    
    <h3>New Wheel styles for summer</h3>

    <section class="offer1">
        
        <div class="fourImages">
            <div class="img1">
                <p>Available from 20-26"</p>
            </div>
            <div class="img2">
                <p>1 Piece, 2 Piece or 3 Piece Configuration.</p>
            </div>
            <div class="img3">
                <p>Regular or Floating Center Cap</p>
            </div>
            <div class="img4">
                <p>Any Surface Finish / Color Combinations possible</p>
            </div>
        </div>
       
        <div class="description2">
             <hr>
            <p>Pricing is determined per customer request.</p>  
            <p>Starting from $10,000 USD</p>
        </div>

    </section>
{% endblock %}  
    <footer>
        <div id="line"></div>
        <p>©Copyright 2023 by Mateusz</p>
    </footer>

    <script defer src="{% static 'main.js'%}"></script>
    <script  src="{% static 'searchBar.js'%}"></script>
</body>
</html>

wheelShop/templates/parts.html
{% extends 'mainHero.html'%}
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Parts</title>
</head>
<body>
    
    {% block mainWheelSite %}
    
    <link rel="stylesheet" href="{% static 'parts.css' %}">
    <h2>CHECK  THE <em>1-PIECE/  2-PIECE/  3-PIECE </em>  HIGH  QUALITY  WHEELS</h2>
    <hr>
    {% for wheel in wheels %}
    {% if forloop.counter0|divisibleby:2 %}
      </section>
      <section class="offerWheels">
    {% endif %}
    <div class="offerBlok">
        
        <img src="{{ wheel.image }}" alt="">
        <p>{{ wheel.name }} {{ wheel.size }}"" </p>
        <p> <em>price</em>  {{ wheel.price }}$</p>
        <p>Only {{ wheel.leftOnStock }} left</p>
               {% if wheel.leftOnStock > 0 %}
            <form action="{% url 'wheelShop:add_to_cart' wheel.id %}" method="post">
          {% csrf_token %}
          <input class="buyBtn" type="submit" value="BUY" >
          <div>
            <select class="amount" name="amount">
              <option value="1">1</option>
              <option value="2">2</option>
              <option value="3">3</option>
              <option value="4">4</option>
            </select>
          </div>
        </form>
        {% else %}
            <input class="buyBtn" type="submit" value="None" >
        {% endif %}
        
           
    </div>
  {% endfor %}
  </section>
    <script src="{% static 'parts.js' %}"></script>
    {% endblock %}
    
</body>
</html>

wheelShop/templates/profile.html
{% extends 'mainHero.html' %}
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Profile</title>
</head>
<body>
    
    {% block mainWheelSite %}
    <link rel="stylesheet" href="{% static 'search.css' %}">
    <h1>{{name}} Profile</h1>
    <div class="searchResults">
          <hr>
        <img src="{{auth0_user.extra_data.picture}}" alt="Profile image" width="50px">
        
       <p> {{user_data}} </p> 
    </div>

            
        
    {% endblock mainWheelSite %}
        
</body>
</html>

wheelShop/templates/searched.html
{% extends 'mainHero.html'%}
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>About</title>
</head>
<body >
    {% block mainWheelSite %}
    <link rel="stylesheet" href="{% static 'search.css' %}">
    <link rel="stylesheet" href="{% static 'parts.css' %}">

        <hr>
        <div class="searchResults">
              {% if parts %}
           {% for part in parts %}
        {% if forloop.counter0|divisibleby:3 %}
         
          <section class="offerWheels">
        {% endif %}
        <div class="offerBlok">
            
            <img src="{{ part.image }}" alt="">
            <p>{{ part.name }} {{ part.size }}"" </p>
            <p> <em>price</em>  {{ part.price }}$</p>
            <p>Only {{ part.leftOnStock }} left</p>
            <form action="{% url 'wheelShop:add_to_cart' part.id %}" method="post">
              {% csrf_token %}
              <input class="buyBtn" type="submit" value="BUY" >
              <div>
                <select class="amount" name="amount">
                  <option value="1">1</option>
                  <option value="2">2</option>
                  <option value="3">3</option>
                  <option value="4">4</option>
                </select>
              </div>
            </form>
            
               
        </div>
      {% endfor %}
        
        {% else %}
            <p id="p00">Nothing has been found, make sure that you typed everything correctly</p>
        {% endif %}
        </div>

        <script src="{% static 'parts.js' %}"></script>
    {% endblock %}
    
</body>
</html>

wheelShop/templates/shoppigBasket.html
{% extends 'mainHero.html' %}
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Buy</title>
</head>
<body>
    
    {% block mainWheelSite %}
    <link rel="stylesheet" href="{% static 'cart.css'%}">
    {% csrf_token %}
    <h1>Cart:</h1>
    <hr>
        <div class="cart-tabl">
            
            <table>
                <tr>
                    <th>ITEM</th>
                    <th>NAME</th>
                    <th>PRICE</th>
                    <th>QUANTITY</th>
                    <th><em>Click to remove</em> </th>
                    
                </tr>
            </table>
            {% for wheel_item in wheel_items %}
            <table>
                <tr>
                    <td><img width="100px" src="{{ wheel_item.image }}" class="img-fluid rounded-start" alt="{{ wheel_item.name }}"></td>
                    <td>{{ wheel_item.name }}</td>
                    <td>{{ wheel_item.price }}</td>
                    <td>{{ wheel_item.quantity }}</td>
                    <td>
                        <form action="{% url 'wheelShop:remove_from_cart' wheel_id=wheel_item.id %}" method="post">
                            {% csrf_token %}
                            <input type="hidden" name="wheel_id" value="{{ wheel_item.id }}">
                            <input class="cc-btn" type="submit" value="Remove">
                    </td>
                </tr>
               
            </form>
            </table>
            
            {% endfor %}
        </div>

        <form class="card-clear-all" action="{% url 'wheelShop:shoppingBasket' %}" method="post">
            {% csrf_token %}
            <input class="cc-btn" type="submit" value="Clear Cart" >
        </form>
            <h5 class="card-title">Order Summary:</h5>
            <p class="card-title">Total: ${{ total }}</p>
            <div class="check">
                <form method="post" name="checkOutBtn" action="{% url 'wheelShop:checkout'%}">
                    {% csrf_token %}
                    <button type="submit"  >Checkout</button>
                </form>
                

            </div>
            
            <hr>

            

    {% endblock mainWheelSite %}
        
</body>
</html>

wheelShop/templates/success.html
{% extends 'mainHero.html' %}
{% load static %}

<!DOCTYPE html>
<html>
<head>
  <title>Checkout canceled</title>
</head>
<body>
    
    {% block mainWheelSite %}
    <section style="font-weight: bold; text-align: center; height: 70vh;">
        <p>
          We appreciate your business! If you have any questions, please email
          <a style="text-decoration: none;" href="mailto:orders@example.com">orders@example.com</a>.
        </p>
      </section>
    {% endblock mainWheelSite %}
        

</body>
</html>